Title: Errors
Author: Jon Reades
Theme: casa notes
Palette: Purple

Size: Wide
---
Layout: Title
# Ooops, I did it Again...

---
> We all make mistakes, it's how we deal with them that matters. It's the same in Python: understanding and handling errors is the key to good code.

---
## Helpfully...

Python will always try to tell you what it **thinks** when wrong: "I didn't understand what you meant by this..." or "I'm sorry, I can't let you do that Dave..."

The challenges are:
1. Python tends to give you a *lot* of information about the error: this can be very helpful for programmers dealing with complex problems and **totally overwhelming** for beginners.
2. That what Python thinks the problem is doesn't always line up with where the problem *actually* is. In cases of syntax, for instance, the problem *could* be an unclosed parenthesis **three lines earlier**!

---
### Challenge 1
That the 'error' isn't always the error...
```
total = 0
print("About to start loop"
for i in range(1,10):
  total += i
print(total)
```
This outputs:
```
print("About to start loop"
... for i in range(1,10):
  File "<stdin>", line 2
    for i in range(1,10):
                        ^
SyntaxError: invalid syntax
>>>   total += i
  File "<stdin>", line 1
    total += i
    ^
IndentationError: unexpected indent
```

---
### Challenge 2

> See Challenge 1.

```
print("About to start loop"
... for i in range(1,10):
  File "<stdin>", line 2
    for i in range(1,10):
                        ^
SyntaxError: invalid syntax
>>>   total += i
  File "<stdin>", line 1
    total += i
    ^
IndentationError: unexpected indent
```


---
## Errors Have Types

> In the same way that variables have types, so do errors. These types give us insight into the issue, but they also allow us to distinguish between different types of errors.

![](mi_question_answer)  Why might the ability to distinguish between different types of errors be helpful?

---
### Trapping Errors

We might reasonably want to distinguish between errors that we could reasonably **expect** or that are **not serious**, from those that **we did not expect** or that **call the results of the program into question**.

^ So it makes sense to think: "Well, let's **try** this and see what happens. If we have a problem of *this* type then it's not serious and we should carry on. But if we have a problem *that* type then we need to stop what we're doing right away."

---
## Python's Approach

Python calls errors **exceptions**, so this leads to:
```python
try:
  ... some code that might fail...
except <Named Error Type>:
  ... what do it if it fails for a specific reason...
except:
  ... what to do if it fails for any other reason...
finally:
  ... always do this, even if it fails...
```
We can even *create* our own problems:
```
raise Exception("Sorry, I can't let you do that, Dave.")
```

---
### For Example

If `x=10` and `y=0` then: 
```
print(x/y)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ZeroDivisionError: division by zero
```

But if you 'trap' the error using `except` then: 
```
try:
  print(x/y)
except ZeroDivisionError:
  print("You can't divide by zero!")
except:
  print("Something has gone wrong.")
finally: 
  print("Division is fun!")

> You can't divide by zero!
> Division is fun!
```

*Note:* if we need to access the *actual* exception: `except ZeroDivisionError as e:`

---
### I'm Just Creating Problems Now

You can trigger your *own* exceptions using `raise`.

```
try:
  print(x/y)
except ZeroDivisionError:
  print("You can't divide by zero!")
  raise Exception("Please don't do that again!")
finally: 
  print("Division is fun!")
```
---

### Errors & More Errors!

If `x=10` and `y=0` then the previous slide's code produces:

```
You can't divide by zero!
Division is fun!
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
Exception: Please don't do that again!
```

---

### Understanding Multiple Errors

1. The code we `try` triggers the `ZeroDivisionError` block.
2. This prints `"You can't divide by zero!"` 
3. We then `raise` a new exception that is *not* caught.
4. The `finally` code executes because it *always* does before Python exits.
5. Python exits with the message from our newly **raised** Exception.

Thus: 'During handling of above (ZeroDivisionError) another exception (our Exception) occurred...'

---

### Typed Errors

We can create our own classes of error very easily:

```
class CustomError(Exception):
  pass
```

This can then be triggered with:

```python
raise CustomError("Our custom error")
```

And (very importantly) this can be caught with:

```python
except CustomError: 
  ... do something ...
```

This means that exceptions could accept custom arguments, perform tidying-up or rollback operations, etc.

---
Layout: SectionTitle
> Understanding exceptions is critical to fixing problems, instead of being overwhelmed by them!

---
## Test-Based Development

We can actually think of exceptions as a way to **develop** our code; for example:
```
# Testing the 'addition' operator
test(1+1, 2)           # Should equal 2
test(1+'1', TypeError) # Should equal TypeError
test('1'+'1', '11')    # Should equal '11'
test(-1+1, 0)          # Should equal 0 
```
Our `test(A,B)` function takes an input (A) and the **expected** output (B) and then compares them. The test returns `True` if A==B and `False` otherwise. 

---
### Unit Tests

Each `test` is called a **Unit Test** because it tests _one thing_ and one thing _only_. So if you had three functions to 'do stuff' then you'd need at least three unit tests. A Unit Test may be composed of one or more **assertions**. Our code on the previous slide contained 4 assertions.

A Unit Test does not mean that your code is correct or will perform properly under all circumstances. It means that your code returns the expected value for a specified set of inputs.

Python considers this approach so important that it's **built in**.

---
### Approach 1

This is an explict assertion to test `fun`:
```
import unittest

def fun(x):
    return x + 1

class MyTest(unittest.TestCase):
    def test(self):
        self.assertEqual(fun(3), 4)
```

---
### Approach 2

This approach uses the 'docstring' (the bits between `"""`) to test the results of the function. This is intended to encourage good documentation of functions using examples: 
```
def square(x):
    """Return the square of x.

    >>> square(2)
    4
    >>> square(-2)
    4
    """
    return x * x

if __name__ == '__main__':
    import doctest
    doctest.testmod()
```

---
### Collaboration & Continuous Integration

The Unit Test approach is often used on collaborative projects, especially in the Open Source world. 

A commit, merge, or pull on GitHub can all be used to trigger the testing process for the *entire* software 'stack': the running of all tests for multiple components is called 'integration testing'.

GitHub offers this service as 'TravisCI', with CI standing for Continuous Integration.

^ This is heavily used by PySAL and other robust FOSS projects since TravisCI is free for FOSS projects!
---
## Resources

- [Handling exceptions](https://www.linkedin.com/learning/python-essential-training-2/handling-exceptions)
- [Reporting errors](https://www.linkedin.com/learning/python-essential-training-2/reporting-errors)
- [Python Custom Exceptions](https://www.programiz.com/python-programming/user-defined-exception)
- [Writing and Using Custom Exceptions in Python](https://www.codementor.io/@sheena/how-to-write-python-custom-exceptions-du107ufv9)
- [Python Documentation](https://docs.python.org/3/tutorial/errors.html)
- [Towards Data Science](https://towardsdatascience.com/how-to-define-custom-exception-classes-in-python-bfa346629bca)
- [Unit Testing in Python](https://www.datacamp.com/community/tutorials/unit-testing-python)
- [Understanding Unit Testing](https://jeffknupp.com/blog/2013/12/09/improve-your-python-understanding-unit-testing/)
- [Testing Your Code](https://docs.python-guide.org/writing/tests/)
- [Getting Started with Testing in Python](https://realpython.com/python-testing/)
- [Python's `unittest` Library](https://docs.python.org/3/library/unittest.html)
- [Video: Unit Testing Your Code](https://www.youtube.com/watch?v=6tNS--WetLI)

